import type { VercelRequest,VercelResponse } from '@vercel/node';

type LeadResult={title:string;company?:string;url:string;snippet:string;source:string;intent:string;score:number;personName?:string;email?:string;phone?:string;contactType?:'phone'|'email'|'both'|'none';contactStatus?:string;isPerson?:boolean};
type Event={type:'log'|'lead'|'rejected'|'done'|'error';source?:string;message?:string;result?:LeadResult;total?:number;eligible?:number};
const UA='Leadcheck/3.0 (+public-intent-lead-discovery)';
const FETCH_TIMEOUT=6500;
const MAX_ANALYZED=180;
function clean(s:string){return s.replace(/\s+/g,' ').trim();}
function decode(s:string){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
function urlAbs(v:string,base?:string){try{return new URL(v,base).toString();}catch{return '';}}
function normUrl(v:string){try{const u=new URL(v);u.hash='';return u.toString();}catch{return v;}}
function host(v:string){try{return new URL(v).hostname.replace(/^www\./,'').toLowerCase();}catch{return '';}}
function htmlText(h:string){return clean(decode(h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')));}
async function fetchText(url:string,headers:Record<string,string>={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),FETCH_TIMEOUT);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.7',...headers}});const text=r.ok?await r.text():'';return{status:r.status,url:r.url||url,text};}catch{return{status:0,url,text:''};}finally{clearTimeout(t);}}
function validPhone(v:string){const d=v.replace(/\D/g,'');return d.length===10||d.length===11||d.length===12||d.length===13;}
function extractPhones(text:string){const raw=[...text.matchAll(/(?:\+?55[\s.-]?)?(?:\(?\d{2}\)?[\s.-]?)?9?\d{4}[\s.-]?\d{4}/g)].map(m=>m[0].trim());return [...new Set(raw.map(v=>v.replace(/\s+/g,' ')).filter(validPhone))].slice(0,8);}
function extractEmails(text:string){return [...new Set([...text.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig)].map(m=>m[0].toLowerCase()).filter(v=>!/(example|wix|wordpress)\./.test(v)))].slice(0,8);}
function extractPersonName(title:string,snippet:string){const text=clean(`${title} ${snippet}`);
 const patterns=[/(?:por|postado por|autor|usu[aá]rio|u\/|de)\s*[:\-]?\s*([A-ZÁÀÃÂÉÊÍÓÔÕÚÇ][A-Za-zÁÀÃÂÉÊÍÓÔÕÚÇáàãâéêíóôõúç'-]{2,}(?:\s+[A-ZÁÀÃÂÉÊÍÓÔÕÚÇ][A-Za-zÁÀÃÂÉÊÍÓÔÕÚÇáàãâéêíóôõúç'-]{2,}){0,2})/,/^([A-ZÁÀÃÂÉÊÍÓÔÕÚÇ][A-Za-zÁÀÃÂÉÊÍÓÔÕÚÇáàãâéêíóôõúç'-]{2,}(?:\s+[A-ZÁÀÃÂÉÊÍÓÔÕÚÇ][A-Za-zÁÀÃÂÉÊÍÓÔÕÚÇáàãâéêíóôõúç'-]{2,}){1,3})\s*[–-]/];
 for(const p of patterns){const m=text.match(p);if(m)return clean(m[1]);}
 return undefined;
}
function looksPerson(title:string,snippet:string){const t=`${title} ${snippet}`.toLowerCase();return /\b(meu|minha|fiz|peguei|contratei|tenho|estou|preciso|quero|não consigo|nao consigo|alguém|alguem|cliente|pessoa|cobrança|cobranca|parcela|salário|salario|folha|holerite)\b/.test(t);}
function scoreIntent(text:string,query:string){const t=text.toLowerCase();let s=25;const words=query.toLowerCase().split(/\s+/).filter(w=>w.length>3);for(const w of words)if(t.includes(w))s+=5;for(const x of ['juros abusivos','juros altos','reduzir parcela','redução de parcela','revisão','revisar contrato','contrato','cobrança indevida','desconto em folha','parcela alta','dívida','divida','portabilidade'])if(t.includes(x))s+=8;return Math.min(100,s);}
function intentQueries(product:string,city:string){const base=product.trim();const phrases=['"juros abusivos"','"juros altos"','"revisão de contrato"','"reduzir parcela"','"parcela alta"','"cobrança indevida"','"desconto em folha"','"quero revisar"','"meu empréstimo"','"minha parcela"'];const qs:string[]=[];for(const p of phrases){qs.push(`"${base}" "${city}" ${p}`);qs.push(`"${city}" ${p} "${base}"`);}for(const site of ['reddit.com','reclameaqui.com.br','youtube.com','facebook.com'])for(const p of phrases.slice(0,6))qs.push(`site:${site} "${base}" ${p} "${city}"`);return [...new Set(qs)].slice(0,36);}
async function searchDuck(q:string){const r=await fetchText(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`);if(!r.text)return[];const out:LeadResult[]=[];for(const block of r.text.split(/result__body/i).slice(1)){const a=block.match(/<a[^>]+class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/i)||block.match(/<a[^>]+href=["']([^"']+)["'][^>]*class=["'][^"']*result__a[^"']*["'][^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;let href=decode(a[1]);const m=href.match(/[?&]uddg=([^&]+)/i);if(m)try{href=decodeURIComponent(m[1]);}catch{}href=urlAbs(href);if(!href)continue;const title=htmlText(a[2]);const snippet=htmlText(block.match(/result__snippet[^>]*>([\s\S]*?)<\/(?:a|div)>/i)?.[1]||'');out.push({title,url:normUrl(href),snippet,source:/reddit|reclameaqui|youtube|facebook/i.test(host(href))?'busca-comunidade':'busca-publica',intent:'',score:0});if(out.length>=10)break;}return out;}
async function searchBing(q:string){const r=await fetchText(`https://www.bing.com/search?format=rss&q=${encodeURIComponent(q)}`,{'accept':'application/rss+xml,application/xml,text/xml;q=0.9'});if(!r.text)return[];const out:LeadResult[]=[];for(const item of r.text.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const b=item[1];const title=clean(decode(b.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''));const link=decode(b.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||'');const snippet=htmlText(b.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||'');if(link)out.push({title,url:normUrl(link),snippet,source:/reddit|reclameaqui|youtube|facebook/i.test(host(link))?'bing-comunidade':'bing-publica',intent:'',score:0});if(out.length>=10)break;}return out;}
async function enrichContact(row:LeadResult){const text=`${row.title} ${row.snippet}`;let personName=extractPersonName(row.title,row.snippet);let phones=extractPhones(text);let emails=extractEmails(text);let page=row.url;
 if((!personName||(!phones.length&&!emails.length))&&row.url){const r=await fetchText(row.url);if(r.text){page=r.url||row.url;const visible=htmlText(r.text).slice(0,120000);phones=[...new Set([...phones,...extractPhones(visible)])].slice(0,8);emails=[...new Set([...emails,...extractEmails(visible)])].slice(0,8);personName=personName||extractPersonName(visible.slice(0,6000),'');}}
 const contactType=phones.length&&emails.length?'both':phones.length?'phone':emails.length?'email':'none';
 const isPerson=Boolean(personName&&looksPerson(row.title,row.snippet));
 return {...row,url:page,personName,email:emails[0],phone:phones[0],contactType,contactStatus:contactType==='none'?'Sem contato público utilizável':`Contato público encontrado (${contactType}).`,isPerson};
}
function emit(res:VercelResponse,event:Event){res.write(JSON.stringify(event)+'\n');}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const product=String(req.body?.query||'').trim();const city=String(req.body?.city||'').trim();if(!product||!city)return res.status(400).json({error:'Produto/interesse e cidade são obrigatórios.'});res.statusCode=200;res.setHeader('Content-Type','application/x-ndjson; charset=utf-8');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('X-Accel-Buffering','no');
 const found=new Set<string>();let analyzed=0,eligible=0,rejected=0;try{const qs=intentQueries(product,city);emit(res,{type:'log',source:'Motor de intenção',message:`Busca pública por pessoas com intenção de ${product} em ${city}.`});emit(res,{type:'log',source:'Filtro de elegibilidade',message:'Só vira lead quando há nome + telefone/celular/WhatsApp ou e-mail publicamente acessível.'});
 for(const q of qs){if(analyzed>=MAX_ANALYZED)break;emit(res,{type:'log',source:'Busca pública',message:`Consultando: ${q}`});const [a,b]=await Promise.all([searchDuck(q),searchBing(q)]);const rows=[...a,...b];emit(res,{type:'log',source:'Busca pública',message:`${rows.length} resultados brutos nesta consulta.`});for(const raw of rows){if(analyzed>=MAX_ANALYZED)break;const key=`${host(raw.url)}|${raw.title.toLowerCase()}|${raw.snippet.slice(0,100).toLowerCase()}`;if(found.has(key))continue;found.add(key);analyzed++;const scored={...raw,intent:product,score:scoreIntent(`${raw.title} ${raw.snippet}`,product)};if(!/juros|parcela|revis|contrat|emprést|emprest|financ|consign|dívida|divida|cobrança|cobranca/i.test(`${raw.title} ${raw.snippet}`))continue;const enriched=await enrichContact(scored);if(enriched.isPerson&&enriched.personName&&(enriched.phone||enriched.email)){eligible++;emit(res,{type:'lead',source:'Lead contatável',result:enriched,total:analyzed,eligible});}else{rejected++;emit(res,{type:'rejected',source:'Filtro de contatos',message:`Descartado: ${enriched.title.slice(0,100)} — é necessário nome público + telefone/celular/WhatsApp ou e-mail.`});}}
 }
 emit(res,{type:'done',total:analyzed,eligible,message:`${eligible} lead(s) contatável(is) encontrados; ${rejected} resultado(s) descartado(s) por falta de contato/identidade.`});res.end();
 }catch(e){emit(res,{type:'error',source:'Motor de intenção',message:e instanceof Error?e.message:'Falha na prospecção.'});res.end();}}
