import type { VercelRequest, VercelResponse } from '@vercel/node';

type Result = {
  title: string; company: string; url: string; snippet: string; email?: string; phone?: string; cnpj?: string; source: string; address?: string; lat?: number; lon?: number;
};
const UA='Leadcheck/1.2 (+public-free-business-discovery)';
const FETCH_TIMEOUT=6500;
const MAX_RESULTS=240;
const MAX_SITES_TO_SCAN=80;
const OVERPASS_ENDPOINTS=['https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter'];
function clean(s:string){return s.replace(/\s+/g,' ').trim()}
function decodeHtml(s:string){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#x27;/g,"'")}
function absoluteUrl(v:string,b?:string){try{return new URL(v,b).toString()}catch{return ''}}
function normalizeUrl(v:string){try{const u=new URL(v);u.hash='';u.search='';u.pathname=u.pathname.replace(/\/$/,'')||'/';return u.toString()}catch{return v}}
function hostOf(v:string){try{return new URL(v).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function looksLikeBusinessSite(url:string){const h=hostOf(url);return !!h&&!/(facebook|instagram|linkedin|youtube|tiktok|twitter|x\.com|google\.|bing\.|duckduckgo\.|yelp\.|tripadvisor\.|wikipedia\.)/i.test(h)}
function htmlText(html:string){return clean(decodeHtml(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')))}
async function fetchText(url:string,init:RequestInit={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),FETCH_TIMEOUT);try{const r=await fetch(url,{...init,headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8',...(init.headers||{})},redirect:'follow',signal:c.signal});return{status:r.status,text:r.ok?await r.text():''}}catch{return{status:0,text:''}}finally{clearTimeout(t)}}
function extractContacts(html:string){const emails=new Set<string>(),phones=new Set<string>(),cnpjs=new Set<string>();for(const m of html.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)){const e=m[0].toLowerCase();if(!/example\.|sentry\.|wixpress\.|schema\.org|cloudflare/i.test(e))emails.add(e)}for(const m of html.matchAll(/(?:\+55[\s.-]?)?(?:\(?\d{2}\)?[\s.-]?)?(?:9[\s.-]?)?\d{4}[\s.-]?\d{4}/g)){const p=clean(m[0]),d=p.replace(/\D/g,'');if(d.length>=10&&d.length<=13)phones.add(p)}for(const m of html.matchAll(/\b\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}\b|\b\d{14}\b/g))cnpjs.add(m[0]);return{email:[...emails][0],phone:[...phones][0],cnpj:[...cnpjs][0]}}
function contactFromTags(t:Record<string,string>={}){return{email:t['contact:email']||t.email||undefined,phone:t['contact:phone']||t.phone||t['contact:mobile']||undefined,cnpj:t['ref:br:cnpj']||undefined}}
function siteFromTags(t:Record<string,string>={}){const r=t.website||t['contact:website']||t.url||'';return r?normalizeUrl(/^https?:\/\//i.test(r)?r:`https://${r}`):''}
function segmentTerms(segment:string){const s=clean(segment).toLowerCase();const groups:Record<string,string[]>={emprestimo:['emprestimo','empréstimo','credito','crédito','consignado','financeira','financiamento'],crédito:['credito','crédito','emprestimo','empréstimo','financiamento','consignado'],credito:['credito','crédito','emprestimo','empréstimo','financiamento','consignado'],advocacia:['advocacia','advogado','advogados','escritorio de advocacia','escritório de advocacia'],imobiliaria:['imobiliaria','imobiliária','imoveis','imóveis','corretora de imoveis','corretora de imóveis'],contabilidade:['contabilidade','contador','contadores','escritorio contabil','escritório contábil'],seguros:['seguros','corretora de seguros','seguro'],despachante:['despachante','despachantes','despachante documentalista','documentalista','documentação de veículos']};const key=Object.keys(groups).find(k=>s.includes(k));return[...new Set([s,...(key?groups[key]:[])])].filter(Boolean)}
async function overpass(segment:string,city:string,emit?:(x:any)=>void){const terms=segmentTerms(segment).map(x=>x.replace(/[\\^$.*+?()[\]{}|]/g,'\\$&').replace(/\s+/g,'[\\s_-]*'));const regex=terms.join('|'),cityEsc=city.replace(/"/g,'\\"');const q=`[out:json][timeout:35];area["name"="${cityEsc}"]["boundary"="administrative"]->.a;(nwr(area.a)["name"~"${regex}",i];nwr(area.a)["brand"~"${regex}",i];nwr(area.a)["operator"~"${regex}",i];nwr(area.a)["description"~"${regex}",i];nwr(area.a)["office"~"${regex}",i];);out center tags;`;for(const endpoint of OVERPASS_ENDPOINTS){try{emit?.({type:'log',level:'info',source:'OpenStreetMap/Overpass',message:`Consultando ${endpoint} para “${segment}” em ${city}…`});const c=new AbortController(),timer=setTimeout(()=>c.abort(),40000);const r=await fetch(endpoint,{method:'POST',headers:{'user-agent':UA,'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body:`data=${encodeURIComponent(q)}`,signal:c.signal});clearTimeout(timer);if(!r.ok){emit?.({type:'log',level:'warn',source:'OpenStreetMap/Overpass',message:`Fonte respondeu HTTP ${r.status}; tentando outra fonte.`});continue}const json=await r.json() as{elements?:any[]};const out:Result[]=[];for(const el of json.elements||[]){const tags=el.tags||{},name=clean(tags.name||tags.brand||tags.operator||'');if(!name)continue;const url=siteFromTags(tags),c=contactFromTags(tags),address=clean([tags['addr:street'],tags['addr:housenumber'],tags['addr:suburb'],tags['addr:city']||city].filter(Boolean).join(', '));const item:Result={title:name,company:name,url,snippet:address||`Empresa encontrada no OpenStreetMap em ${city}.`,source:'openstreetmap-overpass',...c,address,lat:Number(el.lat??el.center?.lat)||undefined,lon:Number(el.lon??el.center?.lon)||undefined};out.push(item);emit?.({type:'lead',lead:item,source:'OpenStreetMap/Overpass'});if(out.length>=MAX_RESULTS)break}if(out.length){emit?.({type:'log',level:'success',source:'OpenStreetMap/Overpass',message:`${out.length} resultados encontrados.`});return out}emit?.({type:'log',level:'info',source:'OpenStreetMap/Overpass',message:'Nenhum resultado nessa fonte.'})}catch(e){emit?.({type:'log',level:'warn',source:'OpenStreetMap/Overpass',message:`Falha de consulta: ${e instanceof Error?e.message:'erro de rede'}.`})}}return[]}
function parseSearchHtml(text:string,source:string):Result[]{const out:Result[]=[];const re=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;for(const m of text.matchAll(re)){let href=decodeHtml(m[1]);const uddg=href.match(/[?&]uddg=([^&]+)/i);if(uddg){try{href=decodeURIComponent(uddg[1])}catch{}}href=absoluteUrl(href);if(!looksLikeBusinessSite(href))continue;const title=htmlText(m[2]);if(title.length<3||title.length>180)continue;out.push({title,company:title,url:normalizeUrl(href),snippet:'Resultado de busca pública.',source});if(out.length>=50)break}return out}
function parseBingRss(text:string):Result[]{const out:Result[]=[];for(const item of text.matchAll(/<item>([\s\S]*?)<\/item>/gi)){const block=item[1];const title=htmlText(block.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||'');const link=decodeHtml(block.match(/<link>([\s\S]*?)<\/link>/i)?.[1]||'');const desc=htmlText(block.match(/<description>([\s\S]*?)<\/description>/i)?.[1]||'');const url=normalizeUrl(link);if(title&&looksLikeBusinessSite(url))out.push({title,company:title,url,snippet:desc||'Resultado Bing público.',source:'bing-public-rss'});if(out.length>=50)break}return out}
async function publicSearch(query:string,emit?:(x:any)=>void){const sources=[{name:'DuckDuckGo',url:`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,kind:'duckduckgo-public-search',parser:parseSearchHtml},{name:'Bing RSS',url:`https://www.bing.com/search?format=rss&q=${encodeURIComponent(query)}`,kind:'bing-public-rss',parser:parseBingRss}];const all:Result[]=[];for(const source of sources){emit?.({type:'log',level:'info',source:source.name,message:`Buscando: ${query}`});const r=await fetchText(source.url);if(!r.text){emit?.({type:'log',level:'warn',source:source.name,message:'Fonte não retornou dados; seguindo para a próxima.'});continue}const rows=source.parser(r.text,source.kind);emit?.({type:'log',level:'success',source:source.name,message:`${rows.length} resultados brutos.`});for(const x of rows){all.push(x);emit?.({type:'lead',lead:x,source:source.name})}}return all}

async function scanSite(result:Result,emit?:(x:any)=>void){if(!result.url||!looksLikeBusinessSite(result.url))return result;emit?.({type:'log',level:'info',source:'Scanner',message:`Abrindo ${result.company||result.url}…`});const first=await fetchText(result.url);if(!first.text){emit?.({type:'log',level:'warn',source:'Scanner',message:`Não foi possível acessar ${result.url} (HTTP ${first.status||'rede'}).`});return result}const c0=extractContacts(first.text);let email=result.email||c0.email,phone=result.phone||c0.phone,cnpj=result.cnpj||c0.cnpj;const links:string[]=[];for(const m of first.text.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const label=htmlText(m[2]);if(/(contato|contact|fale|atendimento|sobre|empresa|quem somos|ouvidoria|sac|servi[cç]os)/i.test(label)){const u=absoluteUrl(decodeHtml(m[1]),result.url);if(u&&hostOf(u)===hostOf(result.url))links.push(u)}}for(const p of ['/contato','/contact','/fale-conosco','/atendimento','/sobre','/quem-somos','/empresa','/ouvidoria','/sac'])links.push(absoluteUrl(p,result.url));for(const u of [...new Set(links)].slice(0,10)){if(email&&phone&&cnpj)break;const page=await fetchText(u);if(!page.text)continue;const c=extractContacts(page.text);email ||= c.email;phone ||= c.phone;cnpj ||= c.cnpj}const updated={...result,email,phone,cnpj};emit?.({type:'lead',lead:updated,source:'Scanner'});return updated}
async function brasilApi(cnpj:string){const digits=cnpj.replace(/\D/g,'');if(digits.length!==14)return null;const r=await fetchText(`https://brasilapi.com.br/api/cnpj/v1/${digits}`,{headers:{accept:'application/json'}});if(!r.text)return null;try{return JSON.parse(r.text)}catch{return null}}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=='POST')return res.status(405).json({error:'Método não permitido.'});const query=clean(String(req.body?.query||'')),city=clean(String(req.body?.city||''));if(!query||!city)return res.status(400).json({error:'Informe segmento e cidade.'});res.statusCode=200;res.setHeader('Content-Type','application/x-ndjson; charset=utf-8');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');const send=(x:any)=>{try{res.write(JSON.stringify(x)+'\n')}catch{}};const found=new Map<string,Result>();const add=(item:Result)=>{const key=item.url?hostOf(item.url):normalizeUrl(`${item.company}|${item.address||city}`);if(!key||found.has(key))return false;found.set(key,item);return true};try{send({type:'start',query,city});const osm=await overpass(query,city,send);for(const item of osm)add(item);const queries=[`"${query}" "${city}" contato telefone`,`"${query}" "${city}" "fale conosco"`,`"${query}" "${city}" endereço`,`"${query}" "${city}" site`];for(const q of queries){for(const item of await publicSearch(q,send))add(item)}const candidates=[...found.values()].slice(0,MAX_SITES_TO_SCAN);send({type:'log',level:'info',source:'Deduplicação',message:`${found.size} empresas candidatas; iniciando análise de sites.`});const scanned:Result[]=[];for(let i=0;i<candidates.length;i+=4){const rows=await Promise.all(candidates.slice(i,i+4).map(x=>scanSite(x,send)));for(const row of rows){scanned.push(row);send({type:'lead',lead:row,source:'resultado-final'})}}const enriched:Result[]=[];for(const item of scanned){let row=item;if(item.cnpj){const data=await brasilApi(item.cnpj);if(data)row={...item,company:item.company||data.nome_fantasia||data.razao_social||item.title,snippet:[item.snippet,data.razao_social||data.nome_fantasia].filter(Boolean).join(' · ')}}enriched.push(row)}send({type:'done',total:enriched.length,sources:['OpenStreetMap/Overpass','DuckDuckGo HTML','Bing HTML','sites empresariais públicos','BrasilAPI sob demanda'],free:true,googlePlaces:false,paidApiRequired:false});res.end()}catch(e){send({type:'error',error:e instanceof Error?e.message:'Falha na busca pública.'});res.end()}}
